baseURL = "https://lightjiao.github.io"
languageCode = "zh-cn"
title = "Lightjiao的博客"
theme = "github-style"
copyright = "© 2019. Theme by <a href=\"https://github.com/MeiK2333/github-style\"><span>github-style</span></a>"

hasCJKLanguage = true
summaryLength = 70

[params]
  author = "Lightjiao"
  description = "Hello world."
  github = "lightjiao"
  email = "lightjiao@gmail.com"
  avatar = "https://www.gravatar.com/avatar/099703df237acafd6c3b962721f959d7.jpg?s=200"
  utterances = "lightjiao/lightjiao.github.io"
  googleCSE = "012421816302566090497:mssmt7t6py4"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
[taxonomies]
  tag = "tags"
  archive = "archives"